name: Test

on: [push, pull_request]

jobs:
  test-linux:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install ripgrep
        uses: ./
        with:
          crate: ripgrep

      - name: Run ripgrep
        run: rg -V

  # test-windows:
  #   name: Test on windows-latest
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v2

  #     - name: Install ripgrep
  #       uses: ./
  #       with:
  #         crate: ripgrep

  #     - name: Run ripgrep
  #       run: rg -V

  test-macos:
    name: Test on macos-latest
    runs-on: macos-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install ripgrep
        uses: ./
        with:
          crate: ripgrep

      - name: Run ripgrep
        run: rg -V
